### PR TITLE
Restored entry for my "line 34" blog

### PR DESCRIPTION
**Pull request by reinhardt**
My blog has gotten lost (but to be fair, it was dormant for over a year). This brings it back.

### CODE REVIEW

**Comment by gforcada** [comment]
You are missing a changelog entry, then travis will be green :+1:

**Comment by reinhardt** [comment]
I don't see any change log entries for added blogs. Is that something I should start now?

**Comment by reinhardt** [comment]
travis says

ERROR: RUN contains undefined ARG or ENV variable on line 17

What does that mean and is that related to my change?

**Comment by gforcada** [comment]
That's what travis was saying, no idea about this new error :confused: 

Let's merge it anyway, the changes are safe and sound. Maybe it will not be deployed automatically... @svx can you shed some light on that? :+1:

**Pull request merged**
