### PR TITLE
Update feeds.cfg to include my blog

### PR DESCRIPTION
**Pull request by birdwell**
I added a plone tag filter so only certain posts will show.

### CODE REVIEW

**Comment by jcbrand** [comment]
@birdwell, @jensens Can this feed be changed to only include entries tagged with Plone? There are now lots of blog posts appearing from this feed which have nothing to do with Plone.

**Comment by jcbrand** [comment]
Looking at the diff, I see that it supposedly already looks for posts tagged with Plone, however, here's a list of articles appearing which have nothing to do with Plone:

* http://josh.postach.io/post/raspberry-pi-tips-tricks-1
* http://josh.postach.io/post/sublime-linter-commands-1
* http://josh.postach.io/post/install-java-jdk-7-on-ubuntu-12-04-javafx-is-included-in-the-installation
* http://josh.postach.io/post/understanding-node-js-exports

**Comment by jensens** [comment]
@jcbrand looking at http://josh.postach.io/feed.xml?tags=plone it seems all plone related, can you point us to a non-related entry?

**Comment by jensens** [comment]
@jcbrand ok, right, @birdwell please fix your tagging or filters

**Pull request merged**
